# Generated by Django 5.2.17 on 2026-09-16 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField(help_text='Hours already used in the 70hr/8day cycle, as submitted')),
                ('start_time', models.DateTimeField(help_text='Rounded down to the 15-minute grid')),
                ('timezone', models.CharField(help_text='Home terminal IANA zone', max_length=64)),
                ('total_miles', models.FloatField()),
                ('route_geometry', models.JSONField(help_text='[[lat, lng], ...]')),
                ('route_bbox', models.JSONField(help_text='[[south, west], [north, east]]')),
                ('summary', models.JSONField()),
                ('limits', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(max_length=16)),
                ('label', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['index'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'index'), name='unique_stop_index_per_trip')],
            },
        ),
        migrations.CreateModel(
            name='LogDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('payload', models.JSONField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.trip')),
            ],
            options={
                'ordering': ['index'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'index'), name='unique_log_day_index_per_trip')],
            },
        ),
    ]
